apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      type: frontend
  template:
    metadata:
      name: my-first-pods
      labels:
        app: nginx
        type: frontend
    spec:
      containers:
      - name: nginx-app
        image: nginx:1.23.4
        env:
          - name: application
            value: front-end-app
          - name: dbname
            valueFrom: 
              configMapKeyRef:
                name: db-configmap          
                key: databasename
        resources:
          requests:
            cpu: "250m"
            memory: "64Mi"
          limits:
            cpu: "500m"
            memory: "128Mi"
