apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
type: Opaque
data:
  dbname: dXJsX3Nob3J0ZW5lcl9kYg==
  username: dXNlcg==
  password: bXlzZWNyZXRwYXNzd29yZA==

  
type field:

  The type field tells Kubernetes how to interpret the data in the secret. 
Use it whenever you need to store custom sensitive data (like DB passwords, tokens, API keys, etc.) that doesnâ€™t fit into any special built-in secret type.
